version: 2.1
jobs:
  e2e:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Install requirements and run e2e scripts
          command: ./e2e/e2e.sh
workflows:
  test:
    jobs:
      - e2e
