version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Install requirements and run build script
          command: |
            mkdir -p ./venv
            virtualenv --python python3 ./venv
            . venv/bin/activate
            pip install --requirement requirements.txt
            pip install --requirement dev_requirements.txt
            ./build
  e2e:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Install requirements and run e2e scripts
          command: |
            cd e2e
            docker-compose version
            docker-compose up --exit-code-from e2e --abort-on-container-exit --build
workflows:
  test:
    jobs:
      - build
      - e2e
