version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Install requirements and run build script
          command: |
            mkdir -p ./venv
            virtualenv --python python3 ./venv
            . venv/bin/activate
            pip install --requirement requirements.txt
            pip install --requirement dev_requirements.txt
            ./build
  e2e:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Install requirements and run e2e scripts
          command: |
            sudo apt-get update
            sudo apt-get install \
              ffmpeg \
              python3-venv \
              --yes
            python3 -m venv ./venv
            . venv/bin/activate
            pip install --requirement requirements.txt
            ./e2e/test-csv-to-yaml
            VIDEOS_DIR=$(mktemp -d)
            ./e2e/test-render-scenes "$VIDEOS_DIR"
            ./e2e/test-publish-to-mediagoblin "$VIDEOS_DIR"
workflows:
  test:
    jobs:
      - build
      - e2e
