
version: '3.2'
services:
  mediagoblin:
    container_name: mediagoblin
    image: mtlynch/mediagoblin
    ports:
      - 8080:6543
    volumes:
      - processed-videos-dir:/publishqueue
      - ./testdata/mediagoblin.ini:/srv/mediagoblin.example.org/mediagoblin/mediagoblin.ini
  e2e:
    container_name: e2e
    build:
      context: ./
    volumes:
      - ../:/app
      - processed-videos-dir:/processed-videos
    working_dir: /app
    entrypoint: /app/e2e/run-all-e2e-tests
    command: ["/processed-videos", "mediagoblin", "/publishqueue"]
    depends_on:
      - mediagoblin
volumes:
  processed-videos-dir: